/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EquacaoSegundo.java
 *
 * Created on 09/02/2012, 11:37:14
 */
package View;

import com.sun.org.apache.xerces.internal.impl.xpath.regex.Match;
import java.awt.Font;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia-Silva
 */
public class EquacaoSegundo extends javax.swing.JFrame {

    double a;
    int b;
    int c;
    int d;
    int e;
    int f;
    double delta;
    double delta1;
    double x;
    double x1;

    /** Creates new form EquacaoSegundo */
    public EquacaoSegundo() {
        initComponents();

        //JFrame fica estatico
        setResizable(false);
        lblequacao1.setVisible(false);
        lblequacao2.setVisible(false);
        lblequacao3.setVisible(false);
        lblequacao5.setVisible(false);
        lblequacao4.setVisible(false);
        lblequacao8.setVisible(false);
        lblequacao9.setVisible(false);
        lblequacao6.setVisible(false);
        lblequacao7.setVisible(false);
        lblequacao10.setVisible(false);

        lbla.setVisible(false);
        lblb.setVisible(false);
        lblc.setVisible(false);
        label5.setVisible(false);
        lbldelta.setVisible(false);
        label5.setText("Δ = ");
        lblbask.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txta = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txtb = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        txtc = new javax.swing.JTextField();
        lblc = new java.awt.Label();
        lblequacao1 = new java.awt.Label();
        lbla = new java.awt.Label();
        lblb = new java.awt.Label();
        lbldelta = new java.awt.Label();
        label5 = new java.awt.Label();
        lblequacao2 = new java.awt.Label();
        lblequacao3 = new java.awt.Label();
        lblequacao4 = new java.awt.Label();
        lblequacao5 = new java.awt.Label();
        lblequacao6 = new java.awt.Label();
        lblequacao7 = new java.awt.Label();
        lblbask = new java.awt.Label();
        lblequacao8 = new java.awt.Label();
        lblequacao9 = new java.awt.Label();
        lblequacao10 = new java.awt.Label();
        btnlimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculo Equação - 2º Grau");
        getContentPane().setLayout(null);

        txta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaActionPerformed(evt);
            }
        });
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaKeyReleased(evt);
            }
        });
        getContentPane().add(txta);
        txta.setBounds(90, 20, 50, 20);

        label1.setText("Valor de \"a\" :");
        getContentPane().add(label1);
        label1.setBounds(10, 24, 80, 20);

        label2.setText("Valor de \"b\" :");
        getContentPane().add(label2);
        label2.setBounds(10, 65, 80, 20);

        txtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbActionPerformed(evt);
            }
        });
        txtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbKeyReleased(evt);
            }
        });
        getContentPane().add(txtb);
        txtb.setBounds(90, 60, 50, 20);

        label3.setText("Valor de \"c\" :");
        getContentPane().add(label3);
        label3.setBounds(10, 106, 80, 20);

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });
        txtc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcFocusLost(evt);
            }
        });
        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcKeyReleased(evt);
            }
        });
        getContentPane().add(txtc);
        txtc.setBounds(90, 100, 50, 20);

        lblc.setText("c");
        getContentPane().add(lblc);
        lblc.setBounds(320, 10, 20, 20);

        lblequacao1.setForeground(new java.awt.Color(204, 0, 0));
        lblequacao1.setText("label4");
        getContentPane().add(lblequacao1);
        lblequacao1.setBounds(160, 20, 150, 20);

        lbla.setText("a");
        getContentPane().add(lbla);
        lbla.setBounds(320, 10, 20, 20);

        lblb.setText("b");
        getContentPane().add(lblb);
        lblb.setBounds(320, 10, 20, 20);

        lbldelta.setText("0");
        getContentPane().add(lbldelta);
        lbldelta.setBounds(190, 130, 60, 20);

        label5.setText("Delta  = ");
        getContentPane().add(label5);
        label5.setBounds(160, 130, 20, 20);

        lblequacao2.setText("label4");
        getContentPane().add(lblequacao2);
        lblequacao2.setBounds(160, 40, 140, 20);

        lblequacao3.setForeground(new java.awt.Color(204, 0, 0));
        lblequacao3.setText("label4");
        getContentPane().add(lblequacao3);
        lblequacao3.setBounds(10, 160, 150, 20);

        lblequacao4.setForeground(new java.awt.Color(0, 0, 0));
        lblequacao4.setText("x2");
        getContentPane().add(lblequacao4);
        lblequacao4.setBounds(200, 190, 140, 20);

        lblequacao5.setForeground(new java.awt.Color(0, 0, 0));
        lblequacao5.setText("x1");
        getContentPane().add(lblequacao5);
        lblequacao5.setBounds(40, 190, 120, 20);

        lblequacao6.setForeground(new java.awt.Color(0, 0, 0));
        lblequacao6.setText("x' = ");
        getContentPane().add(lblequacao6);
        lblequacao6.setBounds(10, 190, 30, 20);

        lblequacao7.setForeground(new java.awt.Color(0, 0, 0));
        lblequacao7.setText("x'' = ");
        getContentPane().add(lblequacao7);
        lblequacao7.setBounds(160, 190, 30, 20);

        lblbask.setText("Bask");
        getContentPane().add(lblbask);
        lblbask.setBounds(10, 140, 130, 20);

        lblequacao8.setForeground(new java.awt.Color(204, 0, 0));
        lblequacao8.setText("label4");
        getContentPane().add(lblequacao8);
        lblequacao8.setBounds(160, 80, 150, 20);

        lblequacao9.setText("label4");
        getContentPane().add(lblequacao9);
        lblequacao9.setBounds(160, 100, 160, 20);

        lblequacao10.setForeground(new java.awt.Color(0, 0, 0));
        lblequacao10.setText("V = ");
        getContentPane().add(lblequacao10);
        lblequacao10.setBounds(10, 220, 260, 20);

        btnlimpar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpar);
        btnlimpar.setBounds(270, 210, 73, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-365)/2, (screenSize.height-278)/2, 365, 278);
    }// </editor-fold>//GEN-END:initComponents

    private void txtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaActionPerformed

    private void txtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcActionPerformed

    private void txtcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcFocusGained
    public static String converterDoubleString(double precoDouble) {
        /*Transformando um double em 2 casas decimais*/
        DecimalFormat fmt = new DecimalFormat("0.00");    //limita o número de casas decimais
        String string = fmt.format(precoDouble);
        String[] part = string.split("[,]");
        String preco = part[0] + "." + part[1];
        return preco;
    }
    private void txtcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcFocusLost
        // TODO add your handling code here:

        String equacao = "";


        if (txta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um valor para a.");
            txta.requestFocus();
        } else {
            // se a > 0
            if (Integer.parseInt(txta.getText()) > 0) {
                if (Integer.parseInt(txta.getText()) > 0) {
                    lbla.setText(txta.getText() + " x²");
                }
                if (Integer.parseInt(txtb.getText()) > 0) {
                    lblb.setText(txtb.getText() + " x");
                }
                if (Integer.parseInt(txtc.getText()) > 0) {
                    lblc.setText(txtc.getText());
                }

                equacao = lbla.getText() + lblb.getText() + lblc.getText();

                lblequacao1.setText(" ax² + " + "bx + " + " c = 0");
                lblequacao1.setVisible(true);

                System.out.println(Integer.parseInt(txtb.getText()) * Integer.parseInt(txtb.getText()));
                a = (Integer.parseInt(txtb.getText()) * Integer.parseInt(txtb.getText()));
                System.out.println(a);
                delta1 = a + (-1) * (4 * Integer.parseInt(txta.getText()) * Integer.parseInt(txtc.getText()));

                System.out.println(delta1);

                // delta1 = a + delta;

                System.out.println(delta1);
                lbldelta.setText(String.valueOf(delta1));
                lblbask.setText("(-1) * b +- √ Δ  / 2 * a");
                lblequacao2.setText(txta.getText() + " x² + " + txtb.getText() + " x + " + txtc.getText() + " = 0");
                lblequacao2.setVisible(true);
                if (delta1 < 0) {

                    JOptionPane.showMessageDialog(null, "Δ = " + delta1 +"\n Δ < 0, a equação não tem soluções reais");
                } else if (delta1 > 0 || delta1 == 0) {

                    x1 = ((((-1) * (Integer.parseInt(txtb.getText()))) + (((-1) * Math.sqrt(delta1))))) / (2 * Integer.parseInt(txta.getText()));
                    x = ((((-1) * (Integer.parseInt(txtb.getText()))) + (Math.sqrt(delta1)))) / (2 * Integer.parseInt(txta.getText()));

                    //  x1 = ((-1) * (e) + ((-1) * Math.sqrt(delta1))) / 2 * d;
                    //  x = ((-1) * (e) + Math.sqrt(delta1)) / 2 * d;

                    System.out.println("x = " + x);
                    System.out.println("x1 = " + x1);
                    lblequacao4.setText(String.valueOf(converterDoubleString(x)));
                    lblequacao5.setText(String.valueOf(converterDoubleString(x1)));

                    if (x >= x1) {
                        lblequacao10.setText("V = { " + converterDoubleString(x1) + ", " + converterDoubleString(x) + "}");
                    } else if (x1 >= x) {
                        lblequacao10.setText("V = { " + converterDoubleString(x) + ", " + converterDoubleString(x1) + "}");
                    }



                    //lblequacao10.setText("V = { " + (x1) + ", " + (x) + " }");
                    lblequacao4.setVisible(true);
                    lblequacao3.setText("(-1) * ( " + (Integer.parseInt(txtb.getText())) + ")" + " +- " + " √ " + delta1 + " / 2 * " + (Integer.parseInt(txta.getText())));
                    lblequacao8.setText("Δ = b² - (4 * a * c)");
                    lblequacao9.setText("Δ = " + (Integer.parseInt(txtb.getText())) + "² - (4 * " + (Integer.parseInt(txta.getText())) + " * " + (Integer.parseInt(txtc.getText())) + ")");
                    lblequacao3.setVisible(true);
                    lblequacao9.setVisible(true);
                    lblequacao8.setVisible(true);
                    lblequacao5.setVisible(true);
                    lblbask.setVisible(true);
                    label5.setVisible(true);
                    lbldelta.setVisible(true);
                    lblequacao6.setVisible(true);
                    lblequacao7.setVisible(true);
                    lblequacao10.setVisible(true);

                }
            }
            //se a < 0
            if (Integer.parseInt(txta.getText()) < 0) {

                //d = (-1) * a
                //e = (-1) * b
                //f = (-1) * c
                d = (-1) * Integer.parseInt(txta.getText());
                e = (-1) * Integer.parseInt(txtb.getText());
                f = (-1) * Integer.parseInt(txtc.getText());

                System.out.println(d);
                System.out.println(e);
                System.out.println(f);

                if (Integer.parseInt(txta.getText()) < 0) {
                    //  lbla.setText("-"+ d + " x²");
                }
                if (Integer.parseInt(txtb.getText()) < 0) {
                    //  lblb.setText("-"+ e + " x");
                }
                if (Integer.parseInt(txtc.getText()) < 0) {
                    //  lblc.setText("-"+ f + "");
                }

                equacao = lbla.getText() + lblb.getText() + lblc.getText();



                System.out.println(e * e);
                a = (e * e);
                System.out.println(a);
                delta = (-1) * (4 * d * f);

                System.out.println(delta);

                delta1 = a + delta;

                lblequacao1.setText("(-1) * " + "(" + (-1) * d + " x² + " + (-1) * e + " x + " + (-1) * f + ")" + " = 0");
                lblequacao1.setVisible(true);
                lblequacao2.setText(d + " x² + " + e + " x + " + f + " = 0");
                lblequacao2.setVisible(true);
                lblbask.setText("(-1) * b +- √ Δ  / 2 * a");

                lblequacao3.setText("(-1) * ( " + e + ")" + " +- " + " √ " + delta1 + " / 2 * " + d);

                lblequacao3.setVisible(true);

                lblequacao8.setText("Δ = b² - (4 * a * c)");
                lblequacao9.setText("Δ = " + e + "² - (4 * " + d + " * " + f + ")");
                lblequacao8.setVisible(true);

                System.out.println(delta1);
                lbldelta.setText(String.valueOf(delta1));
                if (delta1 < 0) {

                    JOptionPane.showMessageDialog(null, "Δ = " + delta1 + "\nEquação inexistente");
                } else {

                    //   x1 = ((((-1) * (Integer.parseInt(txtb.getText())) )+ (((-1) * Math.sqrt(delta1))))) / (2 * Integer.parseInt(txta.getText()));
                    //  x = ((((-1) * (Integer.parseInt(txtb.getText()))) + (Math.sqrt(delta1)))) / (2 * Integer.parseInt(txta.getText()));

                    x1 = ((((-1) * (e) + ((-1)) * (Math.sqrt(delta1))))) / (2 * d);
                    x = ((((-1) * (e)) + (Math.sqrt(delta1)))) / (2 * d);
                    System.out.println("x = " + x);
                    System.out.println("x1 = " + x1);

                    if (x > x1) {
                        lblequacao10.setText("V = { " + converterDoubleString(x1) + ", " + converterDoubleString(x) + "}");
                    } else if (x1 > x) {
                        lblequacao10.setText("V = { " + converterDoubleString(x) + ", " + converterDoubleString(x1) + "}");
                    }
                    lblequacao4.setText(String.valueOf(converterDoubleString(x)));
                    lblequacao5.setText(String.valueOf(converterDoubleString(x1)));
                    //lblequacao10.setText("V = { " + x + ", " + x1 + "}");
                    lblequacao4.setVisible(true);
                    lblequacao9.setVisible(true);
                    lblequacao5.setVisible(true);
                    lblbask.setVisible(true);
                    label5.setVisible(true);
                    lbldelta.setVisible(true);
                    lblequacao6.setVisible(true);
                    lblequacao7.setVisible(true);
                    lblequacao10.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_txtcFocusLost

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        // TODO add your handling code here:
        lblequacao1.setVisible(false);
        lblequacao2.setVisible(false);
        lblequacao3.setVisible(false);
        lblequacao5.setVisible(false);
        lblequacao4.setVisible(false);
        lblequacao8.setVisible(false);
        lblequacao9.setVisible(false);
        lblequacao6.setVisible(false);
        lblequacao7.setVisible(false);
        lblequacao10.setVisible(false);

        lbla.setVisible(false);
        lblb.setVisible(false);
        lblc.setVisible(false);
        label5.setVisible(false);
        lbldelta.setVisible(false);
        label5.setText("Δ = ");
        lblbask.setVisible(false);
        txta.setText("");
        txtb.setText("");
        txtc.setText("");
        txta.requestFocus();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void txtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyReleased
        // TODO add your handling code here:
        txta.setText(txta.getText().replace(",", "").replace(".", "").replace("q", "").replace("w", "").replace("e", "").replace("r", "").replace("t", "").replace("y", "").replace("u", "").replace("i", "").replace("o", "").replace("p", "").replace("´", "").replace("[", "").replace("a", "").replace("s", "").replace("d", "").replace("f", "").replace("g", "").replace("h", "").replace("j", "").replace("k", "").replace("l", "").replace("ç", "").replace("~", "").replace("]", "").replace("|", "").replace("z", "").replace("x", "").replace("c", "").replace("v", "").replace("b", "").replace("n", "").replace("m", "").replace(";", "").replace("<", "").replace(">", "").replace("/", "").replace("^", "").replace("}", "").replace("º", "").replace("{", "").replace("ª", "").replace("'", "").replace("!", "").replace("@", "").replace("$", "").replace("%", "").replace("¨", "").replace("&", "").replace("*", "").replace("(", "").replace(")", "").replace("+", "").replace("_", "").replace(")", "").replace("#", "").replace("?", "").replace("°", ""));
    }//GEN-LAST:event_txtaKeyReleased

    private void txtbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbKeyReleased
        // TODO add your handling code here:
        txtb.setText(txtb.getText().replace(",", "").replace(".", "").replace("q", "").replace("w", "").replace("e", "").replace("r", "").replace("t", "").replace("y", "").replace("u", "").replace("i", "").replace("o", "").replace("p", "").replace("´", "").replace("[", "").replace("a", "").replace("s", "").replace("d", "").replace("f", "").replace("g", "").replace("h", "").replace("j", "").replace("k", "").replace("l", "").replace("ç", "").replace("~", "").replace("]", "").replace("|", "").replace("z", "").replace("x", "").replace("c", "").replace("v", "").replace("b", "").replace("n", "").replace("m", "").replace(";", "").replace("<", "").replace(">", "").replace("/", "").replace("^", "").replace("}", "").replace("º", "").replace("{", "").replace("ª", "").replace("'", "").replace("!", "").replace("@", "").replace("$", "").replace("%", "").replace("¨", "").replace("&", "").replace("*", "").replace("(", "").replace(")", "").replace("+", "").replace("_", "").replace(")", "").replace("#", "").replace("?", "").replace("°", ""));
    }//GEN-LAST:event_txtbKeyReleased

    private void txtcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyReleased
        // TODO add your handling code here:
        txtc.setText(txtc.getText().replace(",", "").replace(".", "").replace("q", "").replace("w", "").replace("e", "").replace("r", "").replace("t", "").replace("y", "").replace("u", "").replace("i", "").replace("o", "").replace("p", "").replace("´", "").replace("[", "").replace("a", "").replace("s", "").replace("d", "").replace("f", "").replace("g", "").replace("h", "").replace("j", "").replace("k", "").replace("l", "").replace("ç", "").replace("~", "").replace("]", "").replace("|", "").replace("z", "").replace("x", "").replace("c", "").replace("v", "").replace("b", "").replace("n", "").replace("m", "").replace(";", "").replace("<", "").replace(">", "").replace("/", "").replace("^", "").replace("}", "").replace("º", "").replace("{", "").replace("ª", "").replace("'", "").replace("!", "").replace("@", "").replace("$", "").replace("%", "").replace("¨", "").replace("&", "").replace("*", "").replace("(", "").replace(")", "").replace("+", "").replace("_", "").replace(")", "").replace("#", "").replace("?", "").replace("°", ""));
    }//GEN-LAST:event_txtcKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EquacaoSegundo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlimpar;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label lbla;
    private java.awt.Label lblb;
    private java.awt.Label lblbask;
    private java.awt.Label lblc;
    private java.awt.Label lbldelta;
    private java.awt.Label lblequacao1;
    private java.awt.Label lblequacao10;
    private java.awt.Label lblequacao2;
    private java.awt.Label lblequacao3;
    private java.awt.Label lblequacao4;
    private java.awt.Label lblequacao5;
    private java.awt.Label lblequacao6;
    private java.awt.Label lblequacao7;
    private java.awt.Label lblequacao8;
    private java.awt.Label lblequacao9;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtb;
    private javax.swing.JTextField txtc;
    // End of variables declaration//GEN-END:variables
}
